apiVersion: v1
kind: Service
metadata:
  name: prometheus-metrics
  namespace: default
  labels:
    app: macro-cycle-hmm
spec:
  selector:
    app: macro-cycle-hmm
  ports:
    - name: metrics
      port: 8000
      targetPort: 8000
  type: ClusterIP

